To Do list: add & remove review
akezeth/To-Do-List pull request #2
Opened 2023-05-11 21:34 UTC by akezeth

- Removed all hardcoded items from the tasks array.
- Implemented a function for adding a new task.
- Implemented a function for deleting a task.
- Implemented a function for editing task descriptions,

2023-05-11 22:20 UTC, zieeco requested changes
Hi @akezeth,

<img height="220" src="https://media3.giphy.com/media/82rEYzUgZbgQM/giphy.gif"/>



Great job so far  👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Great with the CRUD methods. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 22:20 UTC, zieeco commented on src/modules/editTask.js
> +  }
- Hey, let's try to make the edit function work properly by making it to be updated on the localStorage to improve the functionality.

2023-05-11 22:20 UTC, zieeco commented on src/modules/tasks.js
> +
- Hey, I can't seem to delete a task because there seems not to be a delete button from your app. please, kindly fix this.

2023-05-12 15:25 UTC, akezeth commented
- Updated the edit task function to save changes in the local storage.
- Add delete buttons for each tasks.

2023-05-12 17:18 UTC, MeqdamAlqudah approved these changes
Hi @akezeth , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://github.com/akezeth/To-Do-List/assets/74744787/d1a1eb2a-389b-4c03-a4c5-5f3354f12c08)


## Highlights  : 
:+1: delete item functionality 
:+1: save edited items in the localstorage 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 17:28 UTC, merged